# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


include: "rules/common.smk"
include: "rules/bwa_mem.smk"
include: "rules/gatk.smk"
include: "rules/qc.smk"
include: "rules/cnv.smk"
include: "rules/chrm_genotype.smk"
include: "rules/chrm_copies.smk"
include: "rules/other.smk"

rule all:
    input:
      "results/plots/qc/wgs_insert_metrics.pdf",
      "results/plots/cnv/net-037_genomeWide.pdf",
      "results/plots/cnv/net-001a_genomeWide.pdf",
      "results/plots/cnv/net-001b_genomeWide.pdf",
      "results/plots/cnv/net-002_genomeWide.pdf",
      "results/tables/genotypeID/chrM_sampleid.tsv",
      "results/plots/genotypeID/chrM_sampleid.pdf",
      "results/tables/chrM/chrM_copies.tsv",
      "results/plots/chrM/chrM_copies.pdf",

      #rules.indelrealigner.output
#    input: all_input
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.
